# Generated by Django 4.0.4 on 2022-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_News_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
