# Generated by Django 4.0.4 on 2022-05-15 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_News_App', '0002_alter_news_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='kids',
            field=models.CharField(blank=True, max_length=30000000000000000000000000000000000000000000000000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
