# Generated by Django 4.0.4 on 2022-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_News_App', '0003_alter_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=3000000000000000, null=True),
        ),
    ]
