# Generated by Django 4.0.4 on 2022-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_News_App', '0004_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='descendants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='parts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
